# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a32x/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a32x

PRODUCT_COPY_FILES += \
    vendor/samsung/a32x/proprietary/lib/libwvhidl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwvhidl.so \
    vendor/samsung/a32x/proprietary/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/a32x/proprietary/lib/mediadrm/libmockdrmcryptoplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/samsung/a32x/proprietary/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/a32x/proprietary/lib64/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/a32x/proprietary/lib64/mediadrm/libmockdrmcryptoplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/mediadrm/libmockdrmcryptoplugin.so
